INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (1, N'FELICIANO', N'ABASTILLAS', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (2, N'CHARLES', N'AKIATAN', N'POBLACION, CABANGLASAN', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4, N'FLORO', N'ANDAMON', N'LILINGANYON, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (5, N'DIONISIO', N'ARAÑAS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (6, N'JONALYN', N'ARAÑAS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (7, N'PRIMAVERA', N'ARAÑAS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (8, N'CHERYL\ARNOLD', N'ARCADIO', N'KILANGE, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (9, N'FELECIANA', N'ARDEMER', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (10, N'ANGEL', N'ARIGO', N'DAGAT K DAVAO, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (11, N'ALLAN', N'ATUP', N'IMPALAMBONG, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (13, N'SHARON', N'BACLAY', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (14, N'GETULIO', N'BALDAGO', N'BAGONTAAS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (15, N'ISAGANI', N'BALDOMAN', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (16, N'CHERYL', N'BANGIS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (17, N'MARY CHILD', N'BEATINGO', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (18, N'CARLITO', N'BERIAL', N'KALASUNGAY, MALAYBALAY CITY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (19, N'EDGARDO', N'BLANCO', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (20, N'LITO', N'BONILLA', N'LILINGANYON, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (21, N'PABLIO', N'BORBA', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (22, N'JOHN RAY/ROBERTA', N'BORRES', N'BASAG-SAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (23, N'MARJONE/CARIDAD', N'BORRES', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (24, N'BENJAMIN', N'BUGTAI', N'GUINOYORAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (25, N'NORBERTO', N'BULASA', N'MAILAG, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (26, N'ARIEL', N'CAGAANAN', N'BAGONTAAS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (27, N'ARTURO', N'CAGAANAN', N'BAGONTAAS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (28, N'MANUEL', N'CANTEROS', N'POBLACION, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (29, N'AL', N'CASINAS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (30, N'LEONILO', N'CASTROVERDE', N'KAHAPONAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (31, N'EVA MELLANIE', N'CHING', N'POBLACION, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (32, N'GINALYN', N'CONCHA', N'BAGONTAAS, VALENCIA', N'Lantapan', N'Bukidnon', 8722)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (33, N'JOHN', N'CORTES', N'BANTUANON, LANTAPAN', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (34, N'EVANGELINE', N'CUBCUBAN', N'LUROGAN, VELENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (35, N'CONCHITA', N'DAYNOS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (36, N'SUSISO', N'DE GUZMAN', N'LOWER LILINGAYON, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (37, N'WELLINGTON', N'DEVILA', N'SAN CARLOS, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (38, N'HEROLINDA', N'DIOG', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (39, N'JOSEPH', N'DOVERTE', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (40, N'VIRGILLIA', N'ENGLIS', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (41, N'CAROLINA', N'ENTRINA', N'POBLACION, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (42, N'EVANGELINE', N'ESTORGIO', N'LUROGAN, VAENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (43, N'JESSIE', N'EXCLAMADOR', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (44, N'RICHARD', N'FUENTES', N'POB. LANTAPAN', N'Lantapan', N'Bukidnon', 8722)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (45, N'LABITAD FARM', N'G & G', N'SAN CARLOS VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (46, N'VEVENCIA', N'GABATO', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (47, N'SHIPRYL', N'GAMAYON', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (48, N'MARCIANO', N'GENCIANOS', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (49, N'MARISSA', N'GENCIANOS', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (50, N'WELMA', N'GERONA', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (51, N'GIOK', N'LIM', N'POBLACION, MALAYBALAY CITY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (52, N'BRYAN STEVE', N'GO', N'SUGOD, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (53, N'TERESA', N'GUADALUPE', N'COLONIA, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (54, N'STEPHEN JAMES', N'GUIBONE', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (55, N'JOCELYN', N'GUMANOY', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (56, N'JONOLITO', N'GUMANOY', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (57, N'JERMALYN', N'HERRERO', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (58, N'FLAVIO SR.', N'INDINO', N'POBLACION, LANTAPAN, BUKIDNON', N'Lantapan', N'Bukidnon', 8722)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (59, N'TEOFREDO', N'ISIDRO', N'LUMBO, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (60, N'MIGUEL', N'JIMENO', N'BINDULAN, MALAYBALAY CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (61, N'ROSALLE', N'JUROLAN', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (62, N'DIOSDADO', N'KEE', N'IMPALAMBONG, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (63, N'EDUARDO', N'LABITAD', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (64, N'NESTOR', N'LABITAD', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (65, N'RICHAM', N'LABITAD', N'HAGKOL, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (66, N'DANILO JR.', N'LIBRANDO', N'POBLACION, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (67, N'NIDA JOY', N'LIBRANDO', N'POBLACION, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (68, N'MARVIN', N'LLIDO', N'LILINGAYON, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (69, N'ROSALINA', N'LO', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (71, N'RAYMUNDO \NEN', N'MA', N'POBALCION, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (72, N'LORRAINE SHER', N'MABAO', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (73, N'NOREEN', N'MABAO', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (74, N'NORMITA', N'MAESTRADO', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (75, N'JOHN MICKEL', N'MAINIT', N'LUROGAN, VALENCIA CITY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (76, N'ANTONIO', N'MARABE', N'CASISANG, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (77, N'EUFEMIO', N'MARABE', N'POBLACION, MALAYBALAY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (78, N'LENICA', N'MEDINA', N'KILANGE, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (79, N'ALEJANDRO', N'MELECIO', N'POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (80, N'LOYD BRYAN', N'MELECIO', N'POBLACION, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (81, N'ANNIE', N'MELISTON', N'KALASUNGAY, MALAYBALAY CITY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (82, N'VICTOR/LILIA', N'MONTEMAYOR', N'OLD LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (83, N'CESAR', N'MONTEROYO', N'LOURDES, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (84, N'NIARITA', N'MOTEROYO', N'LOURDES, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (85, N'JOHN GAGE', N'NABLE', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (86, N'DORINA', N'NARINGAHON', N'LUROGAN, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (87, N'MARY JANE', N'NEBRIA', N'LUROGAN, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (88, N'ELMA', N'NUGAS', N'LOURDES, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (89, N'LOLITA', N'OBEÑITA', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (90, N'ALEXPE', N'OLIVERIO', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (91, N'BONIFACIO', N'OLIVERIO', N'SAN CARLOS, VALENCIA CITY', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (92, N'ROSALINA', N'OLIVERIO', N'SAN CARLOS, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (93, N'JOSELITO', N'ORA', N'PK 5 POBLACION, VALENCIA', N'Valencia', N'Bukidnon', 8709)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (94, N'ELIZABETH', N'PAGASIAN', N'BRGY. 10, MALAYBALAY CITY', N'Malaybalay', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4583, N'ROEL', N'ZASPA', N'KIPOLOT,PALACAPAO, QUEZON', N'Quezon', N'Bukidnon', 8715)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4590, N'DIONISIO BACAD JR.', N'JIMENEZ', N'PANALSALAN, MARAMAG, BUKIDNON', N'Maramag', N'Bukidnon', 8700)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4591, N'ARVIN', N'ALCANZARIN', N'MANUBIRAY,LAMPANUSAN, BUKIDNON', N'Lantapan', N'Bukidnon', 8722)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4592, N'PRINCESS LEL', N'LIGAN', N'KIBAWE, BUKIDNON', N'Kibawe', N'Bukidnon', 8720)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4593, N'LUZMINDA', N'PANDUMAN', N'KALAGANGAN, SAN FERNANDO, BUKIDNON', N'San Fernando', N'Bukidnon', 8711)
INSERT INTO [dbo].[Customers] ([CustomerID], [FirstName], [LastName], [Address], [City], [State], [ZIP]) VALUES (4594, N'JONJON', N'CORDAVIZ', N'LURUGAN, VALENCIA, BUKIDNON', N'Valencia', N'Bukidnon', 8709)
